#theme: jekyll-theme-minimal
remote_theme: "jekyll/minima"

title: My First Portfolio

description: >
  Hello there! 


author:
  name: Devin Moorjani
  email: "clarkkent4027@gmail.com"

plugins:
  - jekyll-remote-theme



minima:

  # If you don't define the nav pages here, the
  # default is to use  all of the pages.

  nav_pages:
  - about.md
  - howto.md

  social_links:
    - title: GitHub
      icon: github
      url: https://github.com/clarkkent4027
    - title: LinkedIn
      icon: linkedin
      url: https://www.linkedin.com/company/4849605/
    - title: Instagram
      icon: instagram
      url: https://www.instagram.com/DM_4027_/
    - title: Letterbox
      icon: letterboxd
      url: https://www.letterboxd.com/DM4027/

  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized 
  skin: auto




